### ISSUE TITLE
Telegraf instructions out of date

### ISSUE THREAD

**Issue by fishpen0** [atribe/unRAID-docker#12]
https://github.com/influxdata/telegraf/pull/12766 updated telegraf to generate configs on the fly and no longer stores them in the repo.  This broke the link in the original instructions 

I've taken the liberty of proposing a fix https://github.com/atribe/unRAID-docker/pull/11 that swaps the instructions for a single docker command that will create the file for you

**Comment by atribe** [comment]
Thank you for your contribution.
